#bitcount - well, infinite while loop in buggy versions, so not really
breadth_first_search
bucketsort
depth_first_search
detect_cycle
find_first_in_sorted
find_in_sorted
flatten
#gcd
#get_factors
hanoi
#is_valid_parenthesization - original example
kheapsort
knapsack
kth
#lcs_length - except for one NoSuchElementException
#levenshtein
lis
longest_common_subsequence
max_sublist_sum
mergesort
minimum_spanning_tree
next_permutation
pascal
possible_change
powerset
quicksort
reverse_linked_list
rpn_eval
shortest_path_length
shortest_path_lengths
shortest_paths
shunting_yard
sieve
sqrt
subsequences
#to_base
topological_ordering
wrap
